services:
  app:
    container_name: goapp
    image: goapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ROOT=/goapp
      - ENV_PATH=.env
      - LOG_DIR_PATH=/logs
    volumes:
    # Mount the entire logs directory
      - ./logs:/logs