services:
  app:
    container_name: go-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mounted app and error logs
      - ./logs/app.log:./logs/app.log
      - ./logs/error.log:./logs/error.log