basePath: /
host: localhost:8080
info:
  contact:
    email: <email>
    name: Peter Bryant
    url: <url>
  description: Production-ready Go REST API with dependency injection
  license:
    name: Apache 2.0
    url: <url>
  termsOfService: <url>
  title: GoApp REST API
  version: "1.0"
paths:
  /health:
    get:
      description: Do a health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
